spring:  
  application:
    name: doctor-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      register-with-eureka: false
server:  
  port: 8084

